name: 'Set up MATLAB'
description: 'Set up env vars for MATLAB'
author: 'Ray Zimmerman'

inputs:
  os:
    description: 'required for ipopt to distinguish ubuntu-18.04 from 20.04/latest'
    required: false
    default: 'ubuntu-latest'
  ipopt:
    description: 'builds and installs IPOPT interface, if true (default = false)'
    required: false
    default: false
  ipopt-cached:
    description: 'true means IPOPT is installing from a cached build'
    required: false
    default: false
  osqp:
    description: 'builds and installs OSQP interface, if true (default = false)'
    required: false
    default: false
  osqp-cached:
    description: 'true means OSQP is installing from a cached build'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Create Documents/MATLAB dir.
      run: |
        mkdir -p "$HOME/Documents/MATLAB"
        echo "-"
      shell: bash

    - name: Get run-matlab-command (Linux)
      if: runner.os == 'Linux'
      run: |
        wget -O /usr/local/bin/run-matlab-command https://ssd.mathworks.com/supportfiles/ci/run-matlab-command/v2/glnxa64/run-matlab-command
        chmod +x /usr/local/bin/run-matlab-command
      shell: bash
    - name: Get run-matlab-command (macOS)
      if: runner.os == 'macOS'
      run: |
        wget -O /usr/local/bin/run-matlab-command https://ssd.mathworks.com/supportfiles/ci/run-matlab-command/v2/maca64/run-matlab-command
        chmod +x /usr/local/bin/run-matlab-command
      shell: bash
    - name: Get run-matlab-command (Windows)
      if: runner.os == 'Windows'
      run: |
        Invoke-WebRequest `
          -Uri "https://ssd.mathworks.com/supportfiles/ci/run-matlab-command/v2/win64/run-matlab-command.exe" `
          -OutFile "${{ github.workspace }}\\run-matlab-command.exe"
        New-Item -ItemType Directory -Force -Path "${{ github.workspace }}\\bin" | Out-Null
        Move-Item "${{ github.workspace }}\\run-matlab-command.exe" "${{ github.workspace }}\\bin\\run-matlab-command.exe" -Force
      shell: pwsh
    - name: Configure MATLAB (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        export MATLAB_REL=`run-matlab-command "fprintf(regexp(version, '(?<=\().*(?=\))', 'match', 'once'))"`
        echo "MATLAB_REL=${MATLAB_REL}" >> $GITHUB_ENV
        echo "ML_NAME=MATLAB" >> $GITHUB_ENV
        echo "ML_CMD=run-matlab-command" >> $GITHUB_ENV
        echo "ML_PATHVAR=MATLABPATH" >> $GITHUB_ENV
      shell: bash
#         export MATLAB_VER=`matlab -nojvm -batch "fprintf('%s', ver('matlab').Version)"`
#         export MATLAB_REL=`ls /opt/hostedtoolcache/MATLAB`

    - name: Configure MATLAB (Windows)
      if: runner.os == 'Windows'
      run: |
        export MATLAB_REL=`./bin/run-matlab-command.exe "fprintf(regexp(version, '(?<=\().*(?=\))', 'match', 'once'))"`
        echo "MATLAB_REL=${MATLAB_REL}" >> $GITHUB_ENV
        echo "ML_NAME=MATLAB" >> $GITHUB_ENV
        echo "ML_CMD=./bin/run-matlab-command.exe" >> $GITHUB_ENV
        echo "ML_PATHVAR=MATLABPATH" >> $GITHUB_ENV
      shell: bash

    - name: Set MATLAB_VER, ML_VER
      run: |
        export MATLAB_VER=${MATLAB_REL}
        echo "MATLAB_VER=${MATLAB_VER}" >> $GITHUB_ENV
        echo "ML_VER=${MATLAB_VER}" >> $GITHUB_ENV
        echo "-"
      shell: bash

    - name: Build OSQP
      if: ${{ fromJSON(inputs.osqp) && !fromJSON(inputs.osqp-cached) }}
      run: |
        echo "Build OSQP - not cached"
        export OSQP_PATH=$HOME/build/osqp-matlab
        [ ! -d $HOME/build ] && mkdir -p $HOME/build
        cd $HOME/build
        git clone --recursive https://github.com/oxfordcontrol/osqp
        git clone --recurse-submodules https://github.com/oxfordcontrol/osqp-matlab
        mkdir -p $HOME/build/osqp/build
        [ ! -d $HOME/install ] && mkdir -p $HOME/install
        cd $HOME/build/osqp/build
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/install -G "Unix Makefiles" ..
        cmake --build .
        cmake --install .
        echo "OSQP_PATH=${OSQP_PATH}" >> $GITHUB_ENV
        echo "-"
      shell: bash

    - name: Use cached OSQP
      if: ${{ fromJSON(inputs.osqp) && fromJSON(inputs.osqp-cached) }}
      run: |
        echo "Include OSQP - cached - skip build"
        export OSQP_PATH=$HOME/build/osqp-matlab
        echo "OSQP_PATH=${OSQP_PATH}" >> $GITHUB_ENV
        echo "-"
      shell: bash

    - name: Build OSQP MATLAB interface
      if: ${{ fromJSON(inputs.osqp) && !fromJSON(inputs.osqp-cached) }}
      run: |
        echo "Build OSQP interface"
        ls -al $HOME/install/include/osqp
        cd $HOME/build/osqp-matlab
        $ML_CMD "make_osqp"
        ls -al
      shell: bash

    - name: Install OSQP MATLAB interface
      if: ${{ fromJSON(inputs.osqp) }}
      run: |
        echo "Install OSQP interface" 
        echo "$ML_CMD \"addpath('${OSQP_PATH}'); savepath('${GITHUB_WORKSPACE}/pathdef.m')\""
        $ML_CMD "addpath('${OSQP_PATH}'); savepath('${GITHUB_WORKSPACE}/pathdef.m')"
        echo "-"
      shell: bash

    # expects that IPOPT libraries have already been installed
    - name: Fetch IPOPT MATLAB interface (Linux)
      if: ${{ (runner.os == 'Linux') && fromJSON(inputs.ipopt) && !fromJSON(inputs.ipopt-cached) }}
      run: |
        echo "Fetch IPOPT - not cached"
        export IPOPT_PATH=$HOME/build/ipopt
        mkdir -p $IPOPT_PATH
        ${{ inputs.os == 'ubuntu-18.04' }} && curl -SL https://github.com/ebertolazzi/mexIPOPT/raw/master/toolbox/bin/linux_4/ipopt_linux_4.mexa64 --output $IPOPT_PATH/ipopt.mexa64
        ${{ inputs.os != 'ubuntu-18.04' }} && curl -SL https://github.com/ebertolazzi/mexIPOPT/raw/master/toolbox/bin/linux_5/ipopt_linux_5.mexa64 --output $IPOPT_PATH/ipopt.mexa64
        curl -SL https://github.com/ebertolazzi/mexIPOPT/raw/master/toolbox/lib/ipopt_auxdata.m --output $IPOPT_PATH/ipopt_auxdata.m
        curl -SL https://github.com/ebertolazzi/mexIPOPT/raw/master/toolbox/lib/ipopt.m --output $IPOPT_PATH/ipopt.m
        echo "IPOPT_PATH=${IPOPT_PATH}" >> $GITHUB_ENV
        echo "-"
      shell: bash

    - name: Fetch IPOPT MATLAB interface (Windows)
      if: ${{ (runner.os == 'Windows') && fromJSON(inputs.ipopt) && !fromJSON(inputs.ipopt-cached) }}
      run: |
        echo "Fetching of IPOPT MATLAB interface for Windows not yet implemented"
      shell: bash

    - name: Fetch IPOPT MATLAB interface (macOS)
      if: ${{ (runner.os == 'macOS') && fromJSON(inputs.ipopt) && !fromJSON(inputs.ipopt-cached) }}
      run: |
        echo "Fetching of IPOPT MATLAB interface for macOS not yet implemented"
      shell: bash

    - name: Prepare cached IPOPT MATLAB interface
      if: ${{ fromJSON(inputs.ipopt) && fromJSON(inputs.ipopt-cached) }}
      run: |
        echo "Include IPOPT - cached - skip fetch"
        echo "IPOPT_PATH=${IPOPT_PATH}" >> $GITHUB_ENV
        echo "-"
      shell: bash

    - name: Install IPOPT MATLAB interface
      if: ${{ fromJSON(inputs.ipopt) }}
      run: |
        echo "Install IPOPT interface"
        echo "$ML_CMD \"addpath('${IPOPT_PATH}'); savepath('${GITHUB_WORKSPACE}/pathdef.m')\""
        $ML_CMD "addpath('${IPOPT_PATH}'); savepath('${GITHUB_WORKSPACE}/pathdef.m')"
        echo "-"
      shell: bash

branding:
  icon: 'zap'
  color: 'yellow'
