name: CI

# controls when action will run
on:
  # triggers workflow on push events
  push:
  # allows workflow to be triggered manually from Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1

    - name: Configure MATLAB
      uses: ./.

    - name: MATLAB ${{ env.ML_VER }} Installed
      run: $ML_CMD ver

    - name: Configure MATLAB w/JVM
      uses: ./.
      with:
        nojvm: false

    - name: MATLAB ${{ env.ML_VER }} Installed
      run: $ML_CMD ver
