name: CI

# controls when action will run
on:
  # triggers workflow on push events
  push:
  # allows workflow to be triggered manually from Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1

    - name: Configure MATLAB
      uses: ./.

    - name: MATLAB ${{ env.ML_VER }} Installed
      run: $ML_CMD ver

    - name: Configure MATLAB w/JVM
      uses: ./.
      with:
        nojvm: false

    - name: MATLAB ${{ env.ML_VER }} Installed
      run: $ML_CMD ver

    - name: Configure MATLAB w/OSQP
      uses: ./.
      with:
        osqp: true

    - name: MATLAB ${{ env.ML_VER }} with OSQP Installed
      run: $ML_CMD "fprintf('OSQP Version %s installed', osqp().version)"

    - name: Configure MATLAB w/IPOPT
      uses: ./.
      with:
        ipopt: true
        os: ${{ matrix.os }}

    - name: MATLAB ${{ env.ML_VER }} with IPOPT Installed
      run: |
        export IPOPT_TEST_PATH=${GITHUB_WORKSPACE}/.github/ipopt
        ls -al $IPOPT_PATH
        env $ML_PATHVAR=$IPOPT_TEST_PATH $ML_CMD "qps_ipopt([],[1; 1],[1 1],[2],[2],[1; 1],[1; 1],[1; 1],struct('verbose', 2));"
        env $ML_PATHVAR=$IPOPT_TEST_PATH $ML_CMD "if ~have_feature_ipopt(), exit(1); end"
